services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
     - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    depends_on:
      - mongo

  broker:
    image: apache/activemq-classic:5.18.6
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
