services:
  app:
    build: .
    container_name: downloader_bot
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mydatabase
    extra_hosts:
    - "host.docker.internal:host-gateway"
 
  mongo:
    image: mongo:6.0
    container_name: mongodb

  broker:
    image: apache/activemq-classic:5.18.6
    environment:
      - ${ACTIVEMQ_CONNECTION_USER:activemq_user}
      - ${ACTIVEMQ_CONNECTION_PASSWORD:activemq_pass}
